"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useStore } from "@/components/providers";
import { formatPrice } from "@/lib/format";

type PaymentMethod = "invoice" | "card" | "sbp";

export default function CheckoutForm() {
  const router = useRouter(); const { cart, cartTotal, clearCart, user } = useStore();
  const [onlineMethods, setOnlineMethods] = useState<PaymentMethod[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [requestId, setRequestId] = useState("");
  const [form, setForm] = useState({ customerName: "", phone: "", email: user?.email ?? "", address: "", companyName: "", inn: "", comment: "", paymentMethod: "invoice" as PaymentMethod });
  useEffect(() => { void fetch("/api/payments/config").then((response) => response.ok ? response.json() : { onlineMethods: [] }).then((data) => setOnlineMethods(data.onlineMethods ?? [])); }, []);
  const total = useMemo(() => cartTotal, [cartTotal]);
  const methods: { id: PaymentMethod; label: string; description: string }[] = [{ id: "invoice", label: "Счёт для оплаты", description: "Менеджер подтвердит заказ и реквизиты." }, ...(onlineMethods.includes("card") ? [{ id: "card" as const, label: "Банковская карта", description: "Безопасная оплата на странице ЮKassa." }] : []), ...(onlineMethods.includes("sbp") ? [{ id: "sbp" as const, label: "СБП", description: "Оплата на защищённой странице провайдера." }] : [])];
  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (!cart.length) return; setLoading(true); setError("");
    const clientRequestId = requestId || crypto.randomUUID(); if (!requestId) setRequestId(clientRequestId);
    try { const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, clientRequestId, items: cart.map((item) => ({ productId: item.productId, qty: item.qty })) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Не удалось оформить заказ"); clearCart(); if (data.payment?.confirmationUrl) { window.location.assign(data.payment.confirmationUrl); return; } router.replace("/account"); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Не удалось оформить заказ"); } finally { setLoading(false); }
  }
  if (!cart.length) return <main className="mx-auto max-w-3xl px-4 py-16 text-center"><h1 className="font-display text-3xl font-bold">Корзина пуста</h1><p className="mt-3 text-gray-400">Добавьте товары из каталога, чтобы оформить заказ.</p><Link href="/catalog" className="mt-6 inline-block rounded-full bg-[#E0561E] px-5 py-3 text-sm font-semibold">Перейти в каталог</Link></main>;
  return <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><h1 className="font-display text-3xl font-bold sm:text-4xl">Оформление заказа</h1><p className="mt-3 text-sm text-gray-400">Финальная цена и наличие проверяются сервером перед созданием заказа.</p><div className="mt-8 grid grid-cols-1 gap-8 lg:grid-cols-[1.2fr_0.8fr]"><form onSubmit={submit} className="space-y-6 rounded-2xl border border-white/10 bg-[#111317] p-6"><section><h2 className="font-display text-lg font-bold">Контакты</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required className="field" placeholder="Имя" value={form.customerName} onChange={(e) => setForm({ ...form, customerName: e.target.value })}/><input required className="field" placeholder="Телефон" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })}/><input required type="email" className="field sm:col-span-2" placeholder="E-mail" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })}/><textarea className="field sm:col-span-2" rows={3} placeholder="Адрес доставки (при необходимости)" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })}/></div></section><section><h2 className="font-display text-lg font-bold">Оплата</h2><div className="mt-3 space-y-2">{methods.map((method) => <label key={method.id} className="flex cursor-pointer gap-3 rounded-xl border border-white/10 p-3 has-[:checked]:border-[#E0561E]"><input type="radio" name="payment" value={method.id} checked={form.paymentMethod === method.id} onChange={() => setForm({ ...form, paymentMethod: method.id })}/><span><span className="block text-sm font-semibold">{method.label}</span><span className="block text-xs text-gray-400">{method.description}</span></span></label>)}</div></section><textarea className="field" rows={3} placeholder="Комментарий к заказу" value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })}/>{error && <p className="text-sm text-red-400">{error}</p>}<button disabled={loading} className="w-full rounded-full bg-[#E0561E] px-5 py-3 text-sm font-semibold hover:bg-[#F26128] disabled:opacity-60">{loading ? "Оформляем…" : "Подтвердить заказ"}</button></form><aside className="h-fit rounded-2xl border border-white/10 bg-[#111317] p-6"><h2 className="font-display text-lg font-bold">Ваш заказ</h2><ul className="mt-4 space-y-3">{cart.map((item) => <li key={item.productId} className="flex justify-between gap-3 text-sm"><span className="text-gray-300">{item.name} × {item.qty}</span><span>{formatPrice(item.unitPrice * item.qty)}</span></li>)}</ul><div className="mt-5 flex justify-between border-t border-white/10 pt-4"><span className="text-gray-400">Предварительный итог</span><strong className="font-display">{formatPrice(total)}</strong></div>{user?.canUseWholesale && <p className="mt-3 text-xs text-[#E0561E]">Для одобренного B2B-профиля применяется оптовая цена при серверной проверке.</p>}</aside></div></main>;
}
