import { CreditCard, Landmark, QrCode, ShieldCheck } from "lucide-react";
import DeliveryCalculator from "./DeliveryCalculator";

export const metadata = { title: "Доставка и оплата — Generator Store", description: "Условия доставки генераторов, предварительный расчёт и безопасные способы оплаты." };

export default function DeliveryPage() {
  return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><h1 className="font-display text-3xl font-bold sm:text-4xl">Доставка и оплата</h1><p className="mt-3 max-w-2xl text-gray-400">Доставляем генераторы транспортными компаниями и собственным транспортом. Ниже можно рассчитать предварительную стоимость и срок.</p><div className="mt-10"><DeliveryCalculator /></div>
    <section className="mt-16"><h2 className="font-display mb-6 text-2xl font-bold">Способы оплаты</h2><div className="grid grid-cols-1 gap-5 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-[#111317] p-6"><QrCode size={22} className="mb-3 text-[#E0561E]"/><h3 className="font-display mb-1.5 font-semibold">СБП</h3><p className="text-sm text-gray-400">Доступность СБП показывается на оформлении заказа, только если подключён платёжный провайдер.</p></div><div className="rounded-2xl border border-white/10 bg-[#111317] p-6"><CreditCard size={22} className="mb-3 text-[#E0561E]"/><h3 className="font-display mb-1.5 font-semibold">Банковская карта</h3><p className="text-sm text-gray-400">При подключённой интеграции оплата проходит на защищённой странице платёжного провайдера.</p></div><div className="rounded-2xl border border-white/10 bg-[#111317] p-6"><Landmark size={22} className="mb-3 text-[#E0561E]"/><h3 className="font-display mb-1.5 font-semibold">Оплата по счёту</h3><p className="text-sm text-gray-400">Заказ создаётся со счётом, а реквизиты и подтверждение согласуются с менеджером.</p></div></div></section>
    <section className="mt-16 rounded-3xl border border-white/10 bg-[#111317] p-8"><div className="flex items-start gap-4"><ShieldCheck size={24} className="mt-1 shrink-0 text-[#E0561E]"/><div><h2 className="font-display text-xl font-bold">Статус оплаты подтверждается сервером</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-gray-400">Заказ не получает статус «оплачен» по данным браузера. При онлайн-оплате сервер сверяет уведомление с API платёжного провайдера и только после этого обновляет статус заказа. Не публикуйте тестовый QR-код как способ оплаты.</p></div></div></section>
  </main>;
}
